### ISSUE TITLE
فایل dll

### ISSUE THREAD

**Issue by 4M1RHK** [sahand100/FAC#1]
سلام سهند این میگه فایل dll مترو فریموورک میخواد چطوری نصب کنم

**Comment by sahand100** [comment]
سلام
توضیحات how to build رو بخون

**Comment by amirzml** [comment]
Install-Package : Solution is not saved. Please save your solution before managing NuGet packages.
At line:1 char:1
+ Install-Package DotNetZip
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetUnsavedSolution,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by amirzml** [comment]
این رو میگه

**Comment by sahand100** [comment]
Crtl + shift + s بزن قبلش

**Comment by amirzml** [comment]
الان زد 229 ارور ک
![screenshot 610](https://cloud.githubusercontent.com/assets/20270613/18807706/39537948-825b-11e6-99f1-16df27bb130f.png)

**Comment by sahand100** [comment]
How to build 
رو خوندی اصن ؟

**Comment by amirzml** [comment]
خوندم گفته بود باید از nuget اونارو نصب کنم اما نصب کردم فایده نداشت

**Comment by sahand100** [comment]
Dll 
های مترو فریمورکو از 
Toolbox > choose 
ادد کن بعد هرچی اولش مترو بود رو اضاف کن

**Comment by amirzml** [comment]
چطوری اخه من ادد کردم اما بقیشو بلد نیستم
باید چیکار کنم

**Comment by sahand100** [comment]
Toolbox > right click رویه یکجایه خالی > choose item > یک تب هست که توش .net نوشته >load کن dll رو> check کن هرچی اولش metro داره

**Comment by amirzml** [comment]
این کارارو کردم و لود کردم اما بازم ارور میده
![screenshot 612](https://cloud.githubusercontent.com/assets/20270613/18808333/0ae02ca8-826c-11e6-86a3-12d9943f9ba7.png)

**Comment by amirzml** [comment]
ج بده

**Comment by alimardi897** [comment]
سلام من لینک این رو از کدوم صفحه پیدا کنم یکی لطفا راهنمایی کنه خاک پاتونم 
اینم ایدی تلگرامم 
@xXxXmshss
لینک اینو از کدوم طرف پیدا کنم

**Comment by alimardi897** [comment]
لینکش رو کدوم طرف گذاشتین ممنون میشم بگین

**Comment by 4M1RHK** [comment]
چرا ج نمیدی

**Comment by alimardi897** [comment]
بله داداشی

**Comment by alimardi897** [comment]
چیزی میخوای بگی داداش امیر ؟؟

**Comment by sahand100** [comment]
عزیزان اینجا چت روم نیست ...

امیر جان صبر کن دارم ورژن جدید میزنم

**Comment by 4M1RHK** [comment]
من با ورژن جدید کاری ندارم من الا فایل های دی ال ال رو ریختم و نصب کردم الان 230 تا ارور میده داخل تول باکس هم ادد کردم بازم ارور میده چیکارش کنم؟

**Comment by 4M1RHK** [comment]
ج بده

**Comment by 4M1RHK** [comment]
سهند نگفتی اخرشم اینو چیکار کنما
